version: "3.7"
services:
    web:
        build: .
        ports:
            - "8001:80"
        volumes:
            - ./web:/var/www/html/
        depends_on:
            - phpmyadmin
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: usuarios
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d
            - ./mysql/config:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: root
volumes:
    persistent: